# Generated by Django 4.2.3 on 2023-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('camera', models.IntegerField()),
                ('alert_on', models.BooleanField(default=False)),
                ('path', models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\yeore\\OneDrive\\Desktop\\Final Project\\Code\\FYP APP', recursive=True)),
            ],
        ),
    ]
